main.out : Init.c main.c Scheduler.c MsgQueue.c Myhw4.c Thread.c TestCase1.c TestCase2.c TestCase3.c TestCase4.c 
	gcc -o main.out Init.c main.c Scheduler.c Thread.c TestCase1.c TestCase2.c TestCase3.c TestCase4.c MsgQueue.c Myhw4.c 


